module.exports = {
  BADREQUEST: 'BADREQUEST',
  RESOURCECONFLICTERROR: 'RESOURCECONFLICTERROR',
  MISSINGTOKENERROR: 'MISSINGTOKENERROR',
  BADTOKENERROR: 'BADTOKENERROR',
  UNAUTHORIZEDERROR: 'UNAUTHORIZEDERROR',
  RESOURCENOTFOUND: 'RESOURCENOTFOUND',
  FORBIDDENERROR: 'FORBIDDENERROR',
  NOTACCEPTABLEERROR: 'NOTACCEPTABLEERROR',
  METHODNOTALLOWEDERROR: 'METHODNOTALLOWEDERROR',
  UNPROCESSABLEENTITYERROR: 'UNPROCESSABLEENTITYERROR',
  DATABASECONNECTIONERROR: 'DATABASECONNECTIONERROR',
  SERVERERROR: 'SERVERERROR',
};